sudo: required
services:
  - docker

language: go
go:
  - 1.4
  - 1.5
  - tip

matrix:
  allow_failures:
    - go: tip

before_install:
  - docker pull opensuse:13.2
  - docker pull alpine:latest
  - docker pull busybox:latest
  - make build_integration_tests

before_script:
  - go get golang.org/x/tools/cmd/cover
  - go get golang.org/x/tools/cmd/vet
  - go get github.com/golang/lint/golint
  - go get github.com/tools/godep

script:
  - make checks
  - godep go test -v
  - make test_integration
